name: Infra Apply (manual)

on:
  workflow_dispatch:

permissions:
  id-token: write       # Required for AWS OIDC
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  AWS_REGION: "us-east-1"

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lukras-github-deployer-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init -no-color

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event.inputs.auto_approve != 'false'
        working-directory: infra
        run: terraform apply -no-color -auto-approve
