name: Infra Apply (manual)

on:
  workflow_dispatch:

permissions:
  id-token: write       # Required for AWS OIDC
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  AWS_REGION: "us-east-1"
  TF_VAR_telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TF_VAR_telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: ./
        run: terraform init -no-color

      - name: Terraform Plan
        working-directory: ./
        run: terraform plan -no-color -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: ./
        run: terraform apply -no-color -auto-approve -var-file="terraform.tfvars"
